# For dan-bot
DEFAULT_RECURSION = 7  # Arbitrary-ish

# Via game
DEFAULT_HEALTH = 6
TORPEDO_RANGE = 4
SILENCE_RANGE = 4
DIRECTION_WEST = 'W'
DIRECTION_EAST = 'E'
DIRECTION_NORTH = 'N'
DIRECTION_SOUTH = 'S'
POWER_TORPEDO = 'TORPEDO'
POWER_SONAR = 'SONAR'
POWER_MINE = 'MINE'
POWER_SILENCE = 'SILENCE'
ACTION_TRIGGER = 'TRIGGER'
ACTION_SURFACE = 'SURFACE'
ACTION_MOVE = 'MOVE'
