
/** Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {

    public static void main(String[] args) {
        int answer = solve();
        System.out.println("P2 Answer: " + answer);
    }
    
    /** Solves problem in O(n) time and O(1) space. */
    public static int solve() {
        int max = 4000000;
        int sum = 0;
        int previousTerm = 1;
        int currentTerm = 1;
        while (currentTerm <= max) {
            if (currentTerm % 2 == 0) {
                sum += currentTerm;
            }
            int temp = currentTerm;
            currentTerm += previousTerm;
            previousTerm = temp;
        }
        
        return sum;
    }

}